name: Build
on: [push]
jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: echo "Run tests"
        run: ./gradlew test
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build application
        run: ./gradlew build